"use strict";
const REPO="Azotishka/Neuro-assistent",FOLDER="content/issues",BRANCH="gh-pages",DRAFT_KEY="luch:draft:v4",DB_NAME="luch-editor-v1",STORE="files";
const names=["title","issue_number","date","theme","summary","body"],form=$("#issue-form"),chooser=$("#existing"),status=$("#publish-status"),catalogueStatus=$("#catalogue-status"),fileInput=$("#attachment"),photoInput=$("#photo-input"),cameraInput=$("#camera-input"),fileList=$("#file-list"),fileCount=$("#file-count"),filePreview=$("#attachment-preview"),githubLink=$("#github-link"),filenameEl=$("#filename"),dropZone=$("#drop-zone"),autosaveState=$("#autosave-state");
const fields=Object.fromEntries(names.map(n=>[n,$("#"+n)]));const article={title:$("#article-title"),section:$("#article-section"),author:$("#article-author"),lead:$("#article-lead"),text:$("#article-text")};
let issues=[],sourceFile="",attachments=[],saveTimer=0,previewUrl="",detectedArticles=[];
function $(s){return document.querySelector(s)}
const today=()=>{const d=new Date(Date.now()-new Date().getTimezoneOffset()*60000);return d.toISOString().slice(0,10)},clean=v=>String(v??"").trim();
function slug(v){return clean(v).toLowerCase().normalize("NFKD").replace(/[\u0300-\u036f]/g,"").replace(/[^a-z0-9а-яё]+/g,"-").replace(/^-+|-+$/g,"").slice(0,48)}
function chosenFilename(){if(sourceFile)return sourceFile;return (/^\d{4}-\d{2}-\d{2}$/.test(fields.date.value)?fields.date.value:today())+"-issue-"+(slug(fields.issue_number.value).replace(/[^a-z0-9-]/g,"")||"new")+"-"+(slug(fields.title.value).replace(/[^a-z0-9-]/g,"")||"news")+".md"}
function safeFileName(name){const dot=name.lastIndexOf("."),ext=dot>0?name.slice(dot).toLowerCase():"",base=(dot>0?name.slice(0,dot):name).normalize("NFKC").replace(/[\/\\<>:"|?*\x00-\x1f]/g,"_").replace(/\s+/g," ").trim().slice(0,105)||"file";return base+ext.slice(0,12)}
function uniqueName(name,id){const safe=safeFileName(name),dot=safe.lastIndexOf("."),base=dot>0?safe.slice(0,dot):safe,ext=dot>0?safe.slice(dot):"";let out=safe,n=2;while(attachments.some(a=>a.id!==id&&a.name.toLowerCase()===out.toLowerCase()))out=base+"-"+n+++ext;return out}
function attachmentPaths(){return [...attachments].sort((a,b)=>(b.primary?1:0)-(a.primary?1:0)).map(a=>a.published?a.path:"content/files/"+a.name).filter(Boolean)}
function makeMarkdown(){const p=attachmentPaths(),meta={title:clean(fields.title.value),issue_number:clean(fields.issue_number.value),date:clean(fields.date.value),theme:clean(fields.theme.value),summary:clean(fields.summary.value),file:p[0]||"",attachments:JSON.stringify(p.slice(1))};return "---\n"+Object.entries(meta).map(([k,v])=>k+": "+JSON.stringify(v)).join("\n")+"\n---\n\n"+fields.body.value.trim()+"\n"}
function draft(){return {fields:Object.fromEntries(names.map(n=>[n,fields[n].value])),article:Object.fromEntries(Object.entries(article).map(([k,v])=>[k,v.value])),attachments:attachments.map(({id,name,type,size,published,path,primary})=>({id,name,type,size,published,path,primary})),sourceFile,updatedAt:new Date().toISOString()}}
function saveDraft(message=true){localStorage.setItem(DRAFT_KEY,JSON.stringify(draft()));autosaveState.textContent="Сохранено · "+new Intl.DateTimeFormat("ru-RU",{hour:"2-digit",minute:"2-digit"}).format(new Date());if(message)status.textContent="Черновик сохранён на этом устройстве."}
function scheduleSave(){autosaveState.textContent="Сохраняем…";clearTimeout(saveTimer);saveTimer=setTimeout(()=>saveDraft(false),450);updatePreview();updateStats()}
function restoreDraft(){try{const d=JSON.parse(localStorage.getItem(DRAFT_KEY)||"null");if(!d)return false;names.forEach(n=>fields[n].value=d.fields?.[n]||"");Object.entries(article).forEach(([k,v])=>v.value=d.article?.[k]||"");attachments=Array.isArray(d.attachments)?d.attachments:[];sourceFile=d.sourceFile||"";return true}catch{return false}}
function db(){return new Promise((ok,no)=>{const r=indexedDB.open(DB_NAME,1);r.onupgradeneeded=()=>{if(!r.result.objectStoreNames.contains(STORE))r.result.createObjectStore(STORE,{keyPath:"id"})};r.onsuccess=()=>ok(r.result);r.onerror=()=>no(r.error)})}
async function putFile(file,id){const d=await db();return new Promise((ok,no)=>{const r=d.transaction(STORE,"readwrite").objectStore(STORE).put({id,name:file.name,type:file.type,size:file.size,blob:file});r.onsuccess=()=>ok();r.onerror=()=>no(r.error)})}
async function getFile(id){const d=await db();return new Promise((ok,no)=>{const r=d.transaction(STORE).objectStore(STORE).get(id);r.onsuccess=()=>ok(r.result);r.onerror=()=>no(r.error)})}
async function delFile(id){const d=await db();return new Promise((ok,no)=>{const r=d.transaction(STORE,"readwrite").objectStore(STORE).delete(id);r.onsuccess=()=>ok();r.onerror=()=>no(r.error)})}
function human(n){if(!n)return "опубликован";if(n<1024)return n+" Б";if(n<1048576)return (n/1024).toFixed(1)+" КБ";return (n/1048576).toFixed(1)+" МБ"}
function supported(name){return /\.(pdf|doc|docx|odt|rtf|txt|md|ppt|pptx|xls|xlsx|csv|jpg|jpeg|png|webp|zip)$/i.test(name)}
function xmlText(xml){return xml.replace(/<\/(?:w:p|a:p)>/g,"\n").replace(/<(?:w:br|w:tab)[^>]*\/>/g,"\n").replace(/<[^>]+>/g,"").replace(/&amp;/g,"&").replace(/&lt;/g,"<").replace(/&gt;/g,">").replace(/&quot;/g,'"').replace(/&#39;/g,"'").replace(/\n[ \t]+\n/g,"\n\n").replace(/\n{3,}/g,"\n\n").trim()}
async function officeEntries(file,filter){const buf=await file.arrayBuffer(),v=new DataView(buf);let eocd=-1;for(let i=buf.byteLength-22;i>=Math.max(0,buf.byteLength-66000);i--){if(v.getUint32(i,true)===0x06054b50){eocd=i;break}}if(eocd<0)throw Error("ZIP directory not found");const count=v.getUint16(eocd+10,true),start=v.getUint32(eocd+16,true),decoder=new TextDecoder(),out=[];let p=start;for(let n=0;n<count&&p+46<=buf.byteLength;n++){if(v.getUint32(p,true)!==0x02014b50)break;const method=v.getUint16(p+10,true),size=v.getUint32(p+20,true),nameLen=v.getUint16(p+28,true),extraLen=v.getUint16(p+30,true),commentLen=v.getUint16(p+32,true),local=v.getUint32(p+42,true),name=decoder.decode(new Uint8Array(buf,p+46,nameLen));if(filter(name)){const localName=v.getUint16(local+26,true),localExtra=v.getUint16(local+28,true),dataStart=local+30+localName+localExtra,packed=new Uint8Array(buf,dataStart,size);let data;if(method===0)data=packed;else if(method===8&&typeof DecompressionStream!=="undefined"){const stream=new Blob([packed]).stream().pipeThrough(new DecompressionStream("deflate-raw"));data=new Uint8Array(await new Response(stream).arrayBuffer())}else throw Error("Compression not supported");out.push({name,data})}p+=46+nameLen+extraLen+commentLen}return out}
async function importOffice(file,ext){try{const prefix=ext==="docx"?"word/":"ppt/",xmlRule=ext==="docx"?name=>name==="word/document.xml":name=>/^ppt\/slides\/slide\d+\.xml$/i.test(name),entries=await officeEntries(file,name=>xmlRule(name)||name.startsWith(prefix+"media/"));const text=entries.filter(x=>xmlRule(x.name)).sort((a,b)=>a.name.localeCompare(b.name,undefined,{numeric:true})).map(x=>xmlText(new TextDecoder().decode(x.data))).filter(Boolean).join("\n\n");if(text&&!article.text.value.trim()&&!fields.body.value.trim()){const lines=text.split("\n").map(x=>x.trim()).filter(Boolean);if(!article.title.value.trim()&&lines[0])article.title.value=lines.shift().slice(0,180);article.text.value=lines.join("\n\n").slice(0,120000);status.textContent="Текст из "+file.name+" извлечён в быструю статью."}const media=entries.filter(x=>x.name.startsWith(prefix+"media/")).slice(0,12);for(const m of media){const name=m.name.split("/").pop(),type=/\.png$/i.test(name)?"image/png":/\.jpe?g$/i.test(name)?"image/jpeg":/\.webp$/i.test(name)?"image/webp":"";if(type){const img=new File([m.data],name,{type});const id=crypto.randomUUID(),safe=uniqueName(img.name,id);await putFile(img,id);attachments.push({id,name:safe,type,size:img.size,primary:false})}}if(media.length)status.textContent+=" Встроенные изображения также добавлены."}catch(err){status.textContent=file.name+" прикреплён. Автоимпорт текста недоступен в этом браузере."}}
async function addFiles(files){let added=0;for(const f of files){if(!supported(f.name)||f.size>25*1024*1024){status.textContent="Пропущен "+f.name+": формат не поддерживается или файл больше 25 МБ.";continue}const id=crypto.randomUUID(),name=uniqueName(f.name,id);await putFile(f,id);const primary=!attachments.some(a=>a.primary);attachments.push({id,name,type:f.type||"application/octet-stream",size:f.size,primary});added++;const ext=(name.split(".").pop()||"").toLowerCase();if(/^(txt|md|csv)$/.test(ext)){const t=await f.text();if(!article.text.value.trim()&&!fields.body.value.trim())article.text.value=t.slice(0,120000)}else if(/^(docx|pptx)$/.test(ext)){await importOffice(f,ext)}if(!article.title.value.trim()&&!fields.title.value.trim())article.title.value=name.replace(/\.[^.]+$/,"").replace(/[_-]+/g," ")}if(added)status.textContent="Добавлено файлов: "+added+".";saveDraft(false);renderFiles();updatePreview();updateStats()}
async function renderFiles(){fileList.replaceChildren();fileCount.textContent=attachments.length+" "+plural(attachments.length,"файл","файла","файлов");for(const a of attachments){const row=document.createElement("div");row.className="file-row"+(a.primary?" primary-file":"");row.innerHTML='<button type="button" class="star" data-primary title="Сделать основным">'+(a.primary?"★":"☆")+'</button><div class="file-info"><strong>'+escapeHtml(a.name)+'</strong><small>'+escapeHtml(a.type||"файл")+' · '+human(a.size)+(a.primary?" · основной":"")+'</small></div><div class="file-actions"><button type="button" data-open>Открыть</button><button type="button" data-up title="Выше">↑</button><button type="button" data-down title="Ниже">↓</button><button type="button" data-rename title="Переименовать">✎</button><button type="button" data-remove title="Убрать">×</button></div>';
const open=row.querySelector("[data-open]"),remove=row.querySelector("[data-remove]"),primary=row.querySelector("[data-primary]"),rename=row.querySelector("[data-rename]"),up=row.querySelector("[data-up]"),down=row.querySelector("[data-down]");
open.onclick=()=>a.published?window.open("../"+a.path,"_blank","noopener"):previewAttachment(a.id);primary.onclick=()=>{attachments.forEach(x=>x.primary=x.id===a.id);saveDraft(false);renderFiles();updatePreview()};rename.onclick=()=>{const next=prompt("Имя файла",a.name);if(next){a.name=uniqueName(next,a.id);saveDraft(false);renderFiles();updatePreview()}};remove.onclick=async()=>{if(!a.published)await delFile(a.id);const was=a.primary;attachments=attachments.filter(x=>x.id!==a.id);if(was&&attachments[0])attachments[0].primary=true;saveDraft(false);renderFiles();updatePreview()};up.onclick=()=>moveFile(a.id,-1);down.onclick=()=>moveFile(a.id,1);fileList.append(row)}}
function moveFile(id,dir){const i=attachments.findIndex(a=>a.id===id),j=i+dir;if(i<0||j<0||j>=attachments.length)return;[attachments[i],attachments[j]]=[attachments[j],attachments[i]];saveDraft(false);renderFiles()}
async function previewAttachment(id){const rec=await getFile(id);if(!rec){status.textContent="Локальная копия файла недоступна. Добавь файл заново.";return}if(previewUrl)URL.revokeObjectURL(previewUrl);previewUrl=URL.createObjectURL(rec.blob);filePreview.replaceChildren();const ext=rec.name.split(".").pop().toLowerCase();if(ext==="pdf"){const f=document.createElement("iframe");f.src=previewUrl;f.title=rec.name;filePreview.append(f)}else if(/^(jpg|jpeg|png|webp)$/.test(ext)){const img=document.createElement("img");img.src=previewUrl;img.alt=rec.name;filePreview.append(img)}else{const box=document.createElement("div");box.className="file-open";box.innerHTML="<b>"+escapeHtml(rec.name)+"</b><p>Файл сохранён целиком вместе со встроенным текстом, изображениями и оформлением.</p>";const a=document.createElement("a");a.href=previewUrl;a.download=rec.name;a.textContent="Открыть / скачать";box.append(a);filePreview.append(box)}}
function escapeHtml(v){return String(v??"").replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;").replace(/'/g,"&#39;")}
function md(src){const safe=escapeHtml(src);return safe.split(/\n{2,}/).map(block=>{const s=block.trim();if(!s)return"";if(s==="---")return"<hr>";if(s.startsWith("### "))return"<h3>"+inline(s.slice(4))+"</h3>";if(s.startsWith("## "))return"<h2>"+inline(s.slice(3))+"</h2>";if(s.startsWith("# "))return"<h1>"+inline(s.slice(2))+"</h1>";if(s.split("\n").every(x=>/^[-*] /.test(x)))return"<ul>"+s.split("\n").map(x=>"<li>"+inline(x.slice(2))+"</li>").join("")+"</ul>";if(s.split("\n").every(x=>/^\d+\. /.test(x)))return"<ol>"+s.split("\n").map(x=>"<li>"+inline(x.replace(/^\d+\. /,""))+"</li>").join("")+"</ol>";if(s.startsWith("&gt; "))return"<blockquote>"+inline(s.slice(5).replace(/\n/g," "))+"</blockquote>";return"<p>"+inline(s.replace(/\n/g,"<br>"))+"</p>"}).join("")}
function inline(s){return s.replace(/\*\*(.+?)\*\*/g,"<strong>$1</strong>").replace(/\*(.+?)\*/g,"<em>$1</em>").replace(/\[([^\]]+)\]\((https?:\/\/[^)]+)\)/g,'<a href="$2" target="_blank" rel="noopener noreferrer">$1</a>')}
function updatePreview(){const p=attachmentPaths();$("#preview-meta").textContent=[fields.issue_number.value&&"№ "+fields.issue_number.value,fields.date.value,fields.theme.value].filter(Boolean).join(" · ")||"Черновик";$("#preview-heading").textContent=fields.title.value||"Новый выпуск";$("#preview-summary").textContent=fields.summary.value;$("#preview-body").innerHTML=md(fields.body.value||"Здесь появится текст выпуска…")+(p.length?'<div class="preview-files"><b>Материалы: '+p.length+'</b><span>'+p.map(x=>escapeHtml(x.split("/").pop())).join(" · ")+"</span></div>":"");filenameEl.textContent=chosenFilename();const base="https://github.com/"+REPO;githubLink.href=sourceFile?base+"/edit/"+BRANCH+"/"+FOLDER+"/"+encodeURIComponent(sourceFile):base+"/new/"+BRANCH+"/"+FOLDER+"?filename="+encodeURIComponent(chosenFilename())}
function updateStats(){const text=fields.body.value.trim(),words=text?text.split(/\s+/).length:0,articles=(text.match(/^##\s+/gm)||[]).length;$("#word-count").textContent=words+" "+plural(words,"слово","слова","слов");$("#char-count").textContent=text.length+" "+plural(text.length,"знак","знака","знаков");$("#article-count").textContent=articles?"· "+articles+" "+plural(articles,"статья","статьи","статей"):""}
function plural(n,one,few,many){const x=Math.abs(n)%100,y=x%10;return x>10&&x<20?many:y>1&&y<5?few:y===1?one:many}
function fill(issue,origin=""){names.forEach(n=>fields[n].value=clean(issue[n]));sourceFile=origin;attachments=[];if(issue.file)attachments.push({id:"published-main",name:String(issue.file).split("/").pop(),type:"опубликованный файл",size:0,published:true,path:issue.file,primary:true});if(Array.isArray(issue.attachments))issue.attachments.forEach((p,i)=>attachments.push({id:"published-"+i,name:String(p).split("/").pop(),type:"опубликованный файл",size:0,published:true,path:p,primary:!issue.file&&i===0}));updatePreview();updateStats();renderFiles()}
async function loadIssues(){try{const r=await fetch("../content/issues.json",{cache:"no-store"});if(!r.ok)throw Error();issues=await r.json();issues.forEach((x,i)=>{const o=document.createElement("option");o.value=String(i);o.textContent=(x.issue_number?"№ "+x.issue_number+" · ":"")+x.title;chooser.append(o)});catalogueStatus.textContent="Опубликовано выпусков: "+issues.length+". Черновик сохраняется автоматически."}catch{catalogueStatus.textContent="Архив недоступен, но локальный редактор продолжает работать."}}
function clearArticle(){Object.values(article).forEach(x=>x.value="");article.section.value="Новости";article.title.focus()}
function addArticle(){const title=clean(article.title.value),text=clean(article.text.value),lead=clean(article.lead.value);if(!title||(!text&&!lead)){status.textContent="Для статьи нужен заголовок и текст или лид.";article.title.focus();return}const meta=[clean(article.section.value),clean(article.author.value)&&"Автор: "+clean(article.author.value)].filter(Boolean).join(" · ");let block="## "+title+"\n\n";if(meta)block+="**"+meta+"**\n\n";if(lead)block+=lead+"\n\n";if(text)block+=text+"\n";const current=fields.body.value.trim();fields.body.value=(current?current+"\n\n---\n\n":"")+block.trim()+"\n";if(!fields.summary.value.trim()&&lead)fields.summary.value=lead.slice(0,600);clearArticle();scheduleSave();status.textContent="Статья добавлена в выпуск."}

async function attachReadyOriginal(file){if(!supported(file.name)||file.size>25*1024*1024)return;const id=crypto.randomUUID(),name=uniqueName(file.name,id);await putFile(file,id);if(!attachments.some(a=>a.primary))attachments.forEach(a=>a.primary=false);attachments.push({id,name,type:file.type||"application/octet-stream",size:file.size,primary:!attachments.some(a=>a.primary)});renderFiles();saveDraft(false)}
function firstLead(text){const p=String(text).split(/\n{2,}/).map(x=>x.trim()).find(x=>x.length>35)||String(text).trim();return p.replace(/^[-–—•]\s*/,"").slice(0,360)}
function normalizeDetected(items){return items.map((a,i)=>({id:"det-"+i,selected:true,title:clean(a.title).replace(/^#+\s*/,"").slice(0,180)||"Статья "+(i+1),section:clean(a.section)||"Материалы выпуска",lead:clean(a.lead)||firstLead(a.body),body:clean(a.body)})).filter(a=>a.body.length>25||a.lead.length>25).slice(0,60)}
function splitTextArticles(text){text=String(text).replace(/\r/g,"").replace(/[ \t]+\n/g,"\n").replace(/\n{3,}/g,"\n\n").trim();if(!text)return[];const mdHeads=[...text.matchAll(/^#{1,3}\s+(.+)$/gm)];if(mdHeads.length){const out=[];for(let i=0;i<mdHeads.length;i++){const start=mdHeads[i].index+mdHeads[i][0].length,end=i+1<mdHeads.length?mdHeads[i+1].index:text.length,body=text.slice(start,end).trim();if(body)out.push({title:mdHeads[i][1],body})}return normalizeDetected(out)}const paras=text.split(/\n{2,}/).map(x=>x.trim()).filter(Boolean);const out=[];let current=null;for(let i=0;i<paras.length;i++){const p=paras[i].replace(/\n+/g," ").trim(),words=p.split(/\s+/).length,next=paras[i+1]||"",heading=p.length>=4&&p.length<=150&&words<=20&&!/[.;,:]$/.test(p)&&next.length>45;if(heading){if(current&&current.body.join("\n\n").length>30)out.push({title:current.title,body:current.body.join("\n\n")});current={title:p,body:[]}}else if(current)current.body.push(paras[i]);else if(!current&&i===0)current={title:p.slice(0,120),body:[]}}if(current&&current.body.join("\n\n").length>20)out.push({title:current.title,body:current.body.join("\n\n")});if(out.length<2){const lines=text.split("\n").map(x=>x.trim()).filter(Boolean),title=lines.shift()||"Материал выпуска";return normalizeDetected([{title,body:lines.join("\n\n")||text}])}return normalizeDetected(out)}
async function extractPdfArticles(file){if(!window.pdfjsLib)throw Error("PDF.js not loaded");pdfjsLib.GlobalWorkerOptions.workerSrc="../assets/vendor/pdf.worker.min.js";const pdf=await pdfjsLib.getDocument({data:new Uint8Array(await file.arrayBuffer())}).promise,lines=[];for(let pageNo=1;pageNo<=pdf.numPages;pageNo++){const page=await pdf.getPage(pageNo),tc=await page.getTextContent({normalizeWhitespace:true}),items=tc.items.filter(x=>x.str&&x.str.trim()).map(x=>({text:x.str.trim(),x:x.transform?.[4]||0,y:x.transform?.[5]||0,w:x.width||0,size:Math.max(Math.abs(x.height||0),Math.hypot(x.transform?.[2]||0,x.transform?.[3]||0),8)})).sort((a,b)=>Math.abs(b.y-a.y)>2?b.y-a.y:a.x-b.x);const rows=[];for(const it of items){let row=rows.find(r=>Math.abs(r.y-it.y)<2.6);if(!row){row={y:it.y,items:[]};rows.push(row)}row.items.push(it)}rows.sort((a,b)=>b.y-a.y);for(const row of rows){row.items.sort((a,b)=>a.x-b.x);let seg=[];const push=()=>{if(!seg.length)return;lines.push({page:pageNo,y:row.y,x:seg[0].x,text:seg.map(x=>x.text).join(" ").replace(/\s+/g," ").trim(),size:Math.max(...seg.map(x=>x.size))});seg=[]};for(const it of row.items){const prev=seg[seg.length-1],gap=prev?it.x-(prev.x+prev.w):0;if(prev&&gap>55)push();seg.push(it)}push()}}
const sizes=lines.map(x=>x.size).filter(Number.isFinite).sort((a,b)=>a-b),median=sizes[Math.floor(sizes.length*.5)]||10,p80=sizes[Math.floor(sizes.length*.8)]||median,threshold=Math.max(median*1.3,p80*.96),junk=/^(луч|лучшее утро четверга|газета|губернаторский лицей|\d{1,2})$/i;let out=[],cur=null;for(const l of lines){const t=l.text.trim(),words=t.split(/\s+/).length,isHead=l.size>=threshold&&t.length>=4&&t.length<=180&&words<=24&&!junk.test(t)&&!/^https?:/i.test(t);if(isHead){if(cur&&cur.body.join("\n\n").length<70&&cur.page===l.page){cur.title=(cur.title+" "+t).slice(0,180);continue}if(cur&&cur.body.join("\n\n").length>35)out.push({title:cur.title,body:cur.body.join("\n\n")});cur={title:t,body:[],page:l.page}}else if(cur&&!junk.test(t))cur.body.push(t)}if(cur&&cur.body.join("\n\n").length>35)out.push({title:cur.title,body:cur.body.join("\n\n")});if(out.length<2)return splitTextArticles(lines.map(x=>x.text).join("\n\n"));return normalizeDetected(out)}
async function extractOfficeArticles(file,ext){const rule=ext==="docx"?name=>name==="word/document.xml":name=>/^ppt\/slides\/slide\d+\.xml$/i.test(name),entries=await officeEntries(file,rule);if(ext==="pptx"){const out=entries.sort((a,b)=>a.name.localeCompare(b.name,undefined,{numeric:true})).map(x=>{const lines=xmlText(new TextDecoder().decode(x.data)).split("\n").map(s=>s.trim()).filter(Boolean);return{title:lines.shift()||"Слайд",body:lines.join("\n\n")}});return normalizeDetected(out)}return splitTextArticles(entries.map(x=>xmlText(new TextDecoder().decode(x.data))).join("\n\n"))}
async function detectReadyNewspaper(file){const ext=(file.name.split(".").pop()||"").toLowerCase();if(ext==="pdf")return extractPdfArticles(file);if(ext==="docx"||ext==="pptx")return extractOfficeArticles(file,ext);if(ext==="txt"||ext==="md")return splitTextArticles(await file.text());throw Error("Формат не поддерживается для авторазбора")}
function renderDetected(){const wrap=$("#detected-wrap"),box=$("#detected-articles");box.replaceChildren();wrap.hidden=!detectedArticles.length;$("#detected-count").textContent=detectedArticles.length+" "+plural(detectedArticles.length,"статья","статьи","статей");detectedArticles.forEach((a,i)=>{const card=document.createElement("article");card.className="detected-card";card.innerHTML='<label class="detected-check"><input type="checkbox" '+(a.selected?"checked":"")+'> <span>Статья '+(i+1)+'</span></label><label>Заголовок<input data-title></label><label>Анонс<textarea data-lead rows="2"></textarea></label><details><summary>Проверить полный текст</summary><textarea data-body rows="8"></textarea></details>';const check=card.querySelector('input[type="checkbox"]'),title=card.querySelector("[data-title]"),lead=card.querySelector("[data-lead]"),body=card.querySelector("[data-body]");title.value=a.title;lead.value=a.lead;body.value=a.body;check.onchange=()=>a.selected=check.checked;title.oninput=()=>a.title=title.value;lead.oninput=()=>a.lead=lead.value;body.oninput=()=>a.body=body.value;box.append(card)})}
async function importReadyNewspaper(file){const progress=$("#import-progress"),note=$("#import-note");progress.hidden=false;$("#detected-wrap").hidden=true;note.textContent="Читаем "+file.name+" локально на устройстве…";try{await attachReadyOriginal(file);detectedArticles=await detectReadyNewspaper(file);if(!detectedArticles.length)throw Error("Не удалось найти статьи");renderDetected();if(!fields.title.value.trim())fields.title.value=file.name.replace(/\.[^.]+$/,"").replace(/[_-]+/g," ");note.textContent="Найдено статей: "+detectedArticles.length+". Проверь заголовки и нажми «Добавить выбранные статьи».";status.textContent="Готовая газета разобрана на отдельные материалы."}catch(e){detectedArticles=[];renderDetected();note.textContent="Авторазбор не удался: "+e.message+". Оригинальный файл всё равно можно оставить приложенным к выпуску."}finally{progress.hidden=true;saveDraft(false);updatePreview()}}
function applyDetected(){const selected=detectedArticles.filter(a=>a.selected);if(!selected.length){status.textContent="Выбери хотя бы одну статью.";return}const blocks=selected.map(a=>"## "+clean(a.title)+"\n\n**"+clean(a.section||"Материалы выпуска")+"**\n\n"+(clean(a.lead)?clean(a.lead)+"\n\n":"")+clean(a.body)).join("\n\n---\n\n"),current=fields.body.value.trim();fields.body.value=(current?current+"\n\n---\n\n":"")+blocks+"\n";if(!fields.summary.value.trim()&&selected[0].lead)fields.summary.value=selected[0].lead.slice(0,600);scheduleSave();updateStats();status.textContent="Добавлено статей: "+selected.length+".";$("#detected-wrap").hidden=true}
$("#newspaper-import").onchange=async e=>{const file=e.target.files?.[0];if(file)await importReadyNewspaper(file);e.target.value=""};
$("#select-all-detected").onclick=()=>{detectedArticles.forEach(a=>a.selected=true);renderDetected()};$("#clear-detected").onclick=()=>{detectedArticles=[];renderDetected();$("#import-note").textContent="Выбери другой файл, чтобы начать заново."};$("#apply-detected").onclick=applyDetected;

const templates={news:{section:"Новости",title:"Заголовок новости",lead:"Самое важное — одним предложением",text:"Что произошло?\n\nКто участвовал?\n\nПочему это важно?"},interview:{section:"Интервью",title:"Интервью с…",lead:"Кто герой интервью и о чём разговор",text:"— Вопрос?\n— Ответ.\n\n— Следующий вопрос?\n— Ответ."},announcement:{section:"Афиша",title:"Скоро в лицее…",lead:"Что, где и когда",text:"Дата и время:\nМесто:\nДля кого:\n\nПодробности:"},opinion:{section:"Мнение",title:"Заголовок колонки",lead:"Главная мысль автора",text:"Тезис.\n\nАргументы и примеры.\n\nВывод."},blank:{section:"",title:"",lead:"",text:""}};
document.querySelectorAll("[data-template]").forEach(b=>b.onclick=()=>{const t=templates[b.dataset.template];article.section.value=t.section;article.title.value="";article.lead.value="";article.text.value="";article.title.placeholder=t.title||"Заголовок статьи";article.lead.placeholder=t.lead||"Короткий лид";article.text.placeholder=t.text||"Текст статьи";article.title.focus();scheduleSave()});
chooser.onchange=()=>{if(chooser.value===""){restoreDraft();renderFiles();updatePreview();updateStats();return}const x=issues[Number(chooser.value)];if(x)fill(x,x.source_file||"")};
fileInput.onchange=async()=>{await addFiles([...fileInput.files]);fileInput.value=""};photoInput.onchange=async()=>{await addFiles([...photoInput.files]);photoInput.value=""};cameraInput.onchange=async()=>{await addFiles([...cameraInput.files]);cameraInput.value=""};
$("#pick-files").onclick=()=>fileInput.click();$("#pick-photos").onclick=()=>photoInput.click();$("#take-photo").onclick=()=>cameraInput.click();
["dragenter","dragover"].forEach(ev=>dropZone.addEventListener(ev,e=>{e.preventDefault();dropZone.classList.add("dragging")}));["dragleave","drop"].forEach(ev=>dropZone.addEventListener(ev,e=>{e.preventDefault();dropZone.classList.remove("dragging")}));dropZone.addEventListener("drop",e=>addFiles([...e.dataTransfer.files]));
document.addEventListener("paste",e=>{const files=[...e.clipboardData.files].filter(f=>f.type.startsWith("image/"));if(files.length){addFiles(files);status.textContent="Изображение из буфера добавлено к выпуску."}});
form.addEventListener("input",scheduleSave);Object.values(article).forEach(x=>x.addEventListener("input",scheduleSave));
$("#save-local").onclick=()=>saveDraft(true);$("#add-article").onclick=addArticle;$("#clear-article").onclick=clearArticle;
$("#new").onclick=()=>{names.forEach(n=>fields[n].value="");fields.date.value=today();attachments=[];sourceFile="";chooser.value="";clearArticle();saveDraft(false);renderFiles();updatePreview();updateStats();status.textContent="Создан новый локальный выпуск."};
$("#clear-local").onclick=()=>{localStorage.removeItem(DRAFT_KEY);status.textContent="Локальный черновик очищен."};
document.querySelectorAll(".toolbar button").forEach(b=>b.onclick=()=>{const t=fields.body,action=b.dataset.action;if(action==="undo"||action==="redo"){t.focus();document.execCommand(action);scheduleSave();return}const start=t.selectionStart,end=t.selectionEnd,sel=t.value.slice(start,end);if(b.dataset.wrap){const [a,z]=b.dataset.wrap.split("|");t.setRangeText(a+sel+z,start,end,"select")}else if(b.dataset.prefix){const line=t.value.lastIndexOf("\n",start-1)+1;t.setRangeText(b.dataset.prefix,line,line,"end")}else if(action==="link"){const url=prompt("Ссылка","https://");if(url)t.setRangeText("["+(sel||"ссылка")+"]("+url+")",start,end,"end")}else if(action==="rule"){t.setRangeText("\n\n---\n\n",start,end,"end")}t.focus();scheduleSave()});
document.addEventListener("keydown",e=>{const mod=e.ctrlKey||e.metaKey;if(mod&&e.key.toLowerCase()==="s"){e.preventDefault();saveDraft(true)}if(mod&&e.key==="Enter"&&(document.activeElement===article.text||document.activeElement===article.title||document.activeElement===article.lead)){e.preventDefault();addArticle()}if(mod&&(e.key.toLowerCase()==="b"||e.key.toLowerCase()==="i")&&document.activeElement===fields.body){e.preventDefault();const mark=e.key.toLowerCase()==="b"?"**":"*",t=fields.body,s=t.selectionStart,en=t.selectionEnd;t.setRangeText(mark+t.value.slice(s,en)+mark,s,en,"select");scheduleSave()}});
$("#download").onclick=()=>{const blob=new Blob([makeMarkdown()],{type:"text/markdown;charset=utf-8"}),a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=chosenFilename();a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);status.textContent="Markdown выпуска сохранён на устройство."};$("#copy").onclick=async()=>{try{await navigator.clipboard.writeText(makeMarkdown());status.textContent="Markdown скопирован."}catch{status.textContent="Браузер запретил копирование — используй «Экспорт .md»."}};
if(!restoreDraft()){fields.date.value=today();article.section.value="Новости"}renderFiles();updatePreview();updateStats();loadIssues();
