"use strict";
const REPO="Azotishka/Neuro-assistent",FOLDER="content/issues",BRANCH="gh-pages",DRAFT_KEY="luch:draft:v4",DB_NAME="luch-editor-v1",STORE="files";
const names=["title","issue_number","date","theme","summary","body"],form=$("#issue-form"),chooser=$("#existing"),status=$("#publish-status"),catalogueStatus=$("#catalogue-status"),fileInput=$("#attachment"),photoInput=$("#photo-input"),cameraInput=$("#camera-input"),fileList=$("#file-list"),fileCount=$("#file-count"),filePreview=$("#attachment-preview"),githubLink=$("#github-link"),filenameEl=$("#filename"),dropZone=$("#drop-zone"),autosaveState=$("#autosave-state");
const fields=Object.fromEntries(names.map(n=>[n,$("#"+n)]));const article={title:$("#article-title"),section:$("#article-section"),author:$("#article-author"),lead:$("#article-lead"),text:$("#article-text")};
let issues=[],sourceFile="",attachments=[],saveTimer=0,previewUrl="";
function $(s){return document.querySelector(s)}
const today=()=>{const d=new Date(Date.now()-new Date().getTimezoneOffset()*60000);return d.toISOString().slice(0,10)},clean=v=>String(v??"").trim();
function slug(v){return clean(v).toLowerCase().normalize("NFKD").replace(/[\u0300-\u036f]/g,"").replace(/[^a-z0-9а-яё]+/g,"-").replace(/^-+|-+$/g,"").slice(0,48)}
function chosenFilename(){if(sourceFile)return sourceFile;return (/^\d{4}-\d{2}-\d{2}$/.test(fields.date.value)?fields.date.value:today())+"-issue-"+(slug(fields.issue_number.value).replace(/[^a-z0-9-]/g,"")||"new")+"-"+(slug(fields.title.value).replace(/[^a-z0-9-]/g,"")||"news")+".md"}
function safeFileName(name){const dot=name.lastIndexOf("."),ext=dot>0?name.slice(dot).toLowerCase():"",base=(dot>0?name.slice(0,dot):name).normalize("NFKC").replace(/[\/\\<>:"|?*\x00-\x1f]/g,"_").replace(/\s+/g," ").trim().slice(0,105)||"file";return base+ext.slice(0,12)}
function uniqueName(name,id){const safe=safeFileName(name),dot=safe.lastIndexOf("."),base=dot>0?safe.slice(0,dot):safe,ext=dot>0?safe.slice(dot):"";let out=safe,n=2;while(attachments.some(a=>a.id!==id&&a.name.toLowerCase()===out.toLowerCase()))out=base+"-"+n+++ext;return out}
function attachmentPaths(){return [...attachments].sort((a,b)=>(b.primary?1:0)-(a.primary?1:0)).map(a=>a.published?a.path:"content/files/"+a.name).filter(Boolean)}
function makeMarkdown(){const p=attachmentPaths(),meta={title:clean(fields.title.value),issue_number:clean(fields.issue_number.value),date:clean(fields.date.value),theme:clean(fields.theme.value),summary:clean(fields.summary.value),file:p[0]||"",attachments:JSON.stringify(p.slice(1))};return "---\n"+Object.entries(meta).map(([k,v])=>k+": "+JSON.stringify(v)).join("\n")+"\n---\n\n"+fields.body.value.trim()+"\n"}
function draft(){return {fields:Object.fromEntries(names.map(n=>[n,fields[n].value])),article:Object.fromEntries(Object.entries(article).map(([k,v])=>[k,v.value])),attachments:attachments.map(({id,name,type,size,published,path,primary})=>({id,name,type,size,published,path,primary})),sourceFile,updatedAt:new Date().toISOString()}}
function saveDraft(message=true){localStorage.setItem(DRAFT_KEY,JSON.stringify(draft()));autosaveState.textContent="Сохранено · "+new Intl.DateTimeFormat("ru-RU",{hour:"2-digit",minute:"2-digit"}).format(new Date());if(message)status.textContent="Черновик сохранён на этом устройстве."}
function scheduleSave(){autosaveState.textContent="Сохраняем…";clearTimeout(saveTimer);saveTimer=setTimeout(()=>saveDraft(false),450);updatePreview();updateStats()}
function restoreDraft(){try{const d=JSON.parse(localStorage.getItem(DRAFT_KEY)||"null");if(!d)return false;names.forEach(n=>fields[n].value=d.fields?.[n]||"");Object.entries(article).forEach(([k,v])=>v.value=d.article?.[k]||"");attachments=Array.isArray(d.attachments)?d.attachments:[];sourceFile=d.sourceFile||"";return true}catch{return false}}
function db(){return new Promise((ok,no)=>{const r=indexedDB.open(DB_NAME,1);r.onupgradeneeded=()=>{if(!r.result.objectStoreNames.contains(STORE))r.result.createObjectStore(STORE,{keyPath:"id"})};r.onsuccess=()=>ok(r.result);r.onerror=()=>no(r.error)})}
async function putFile(file,id){const d=await db();return new Promise((ok,no)=>{const r=d.transaction(STORE,"readwrite").objectStore(STORE).put({id,name:file.name,type:file.type,size:file.size,blob:file});r.onsuccess=()=>ok();r.onerror=()=>no(r.error)})}
async function getFile(id){const d=await db();return new Promise((ok,no)=>{const r=d.transaction(STORE).objectStore(STORE).get(id);r.onsuccess=()=>ok(r.result);r.onerror=()=>no(r.error)})}
async function delFile(id){const d=await db();return new Promise((ok,no)=>{const r=d.transaction(STORE,"readwrite").objectStore(STORE).delete(id);r.onsuccess=()=>ok();r.onerror=()=>no(r.error)})}
function human(n){if(!n)return "опубликован";if(n<1024)return n+" Б";if(n<1048576)return (n/1024).toFixed(1)+" КБ";return (n/1048576).toFixed(1)+" МБ"}
function supported(name){return /\.(pdf|doc|docx|odt|rtf|txt|md|ppt|pptx|xls|xlsx|csv|jpg|jpeg|png|webp|zip)$/i.test(name)}
async function addFiles(files){let added=0;for(const f of files){if(!supported(f.name)||f.size>25*1024*1024){status.textContent="Пропущен "+f.name+": формат не поддерживается или файл больше 25 МБ.";continue}const id=crypto.randomUUID(),name=uniqueName(f.name,id);await putFile(f,id);const primary=!attachments.some(a=>a.primary);attachments.push({id,name,type:f.type||"application/octet-stream",size:f.size,primary});added++;const ext=(name.split(".").pop()||"").toLowerCase();if(/^(txt|md|csv)$/.test(ext)){const t=await f.text();if(!article.text.value.trim()&&!fields.body.value.trim())article.text.value=t.slice(0,120000)}if(!article.title.value.trim()&&!fields.title.value.trim())article.title.value=name.replace(/\.[^.]+$/,"").replace(/[_-]+/g," ")}if(added)status.textContent="Добавлено файлов: "+added+".";saveDraft(false);renderFiles();updatePreview();updateStats()}
async function renderFiles(){fileList.replaceChildren();fileCount.textContent=attachments.length+" "+plural(attachments.length,"файл","файла","файлов");for(const a of attachments){const row=document.createElement("div");row.className="file-row"+(a.primary?" primary-file":"");row.innerHTML='<button type="button" class="star" data-primary title="Сделать основным">'+(a.primary?"★":"☆")+'</button><div class="file-info"><strong>'+escapeHtml(a.name)+'</strong><small>'+escapeHtml(a.type||"файл")+' · '+human(a.size)+(a.primary?" · основной":"")+'</small></div><div class="file-actions"><button type="button" data-open>Открыть</button><button type="button" data-up title="Выше">↑</button><button type="button" data-down title="Ниже">↓</button><button type="button" data-rename title="Переименовать">✎</button><button type="button" data-remove title="Убрать">×</button></div>';
const open=row.querySelector("[data-open]"),remove=row.querySelector("[data-remove]"),primary=row.querySelector("[data-primary]"),rename=row.querySelector("[data-rename]"),up=row.querySelector("[data-up]"),down=row.querySelector("[data-down]");
open.onclick=()=>a.published?window.open("../"+a.path,"_blank","noopener"):previewAttachment(a.id);primary.onclick=()=>{attachments.forEach(x=>x.primary=x.id===a.id);saveDraft(false);renderFiles();updatePreview()};rename.onclick=()=>{const next=prompt("Имя файла",a.name);if(next){a.name=uniqueName(next,a.id);saveDraft(false);renderFiles();updatePreview()}};remove.onclick=async()=>{if(!a.published)await delFile(a.id);const was=a.primary;attachments=attachments.filter(x=>x.id!==a.id);if(was&&attachments[0])attachments[0].primary=true;saveDraft(false);renderFiles();updatePreview()};up.onclick=()=>moveFile(a.id,-1);down.onclick=()=>moveFile(a.id,1);fileList.append(row)}}
function moveFile(id,dir){const i=attachments.findIndex(a=>a.id===id),j=i+dir;if(i<0||j<0||j>=attachments.length)return;[attachments[i],attachments[j]]=[attachments[j],attachments[i]];saveDraft(false);renderFiles()}
async function previewAttachment(id){const rec=await getFile(id);if(!rec){status.textContent="Локальная копия файла недоступна. Добавь файл заново.";return}if(previewUrl)URL.revokeObjectURL(previewUrl);previewUrl=URL.createObjectURL(rec.blob);filePreview.replaceChildren();const ext=rec.name.split(".").pop().toLowerCase();if(ext==="pdf"){const f=document.createElement("iframe");f.src=previewUrl;f.title=rec.name;filePreview.append(f)}else if(/^(jpg|jpeg|png|webp)$/.test(ext)){const img=document.createElement("img");img.src=previewUrl;img.alt=rec.name;filePreview.append(img)}else{const box=document.createElement("div");box.className="file-open";box.innerHTML="<b>"+escapeHtml(rec.name)+"</b><p>Файл сохранён целиком вместе со встроенным текстом, изображениями и оформлением.</p>";const a=document.createElement("a");a.href=previewUrl;a.download=rec.name;a.textContent="Открыть / скачать";box.append(a);filePreview.append(box)}}
function escapeHtml(v){return String(v??"").replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;").replace(/'/g,"&#39;")}
function md(src){const safe=escapeHtml(src);return safe.split(/\n{2,}/).map(block=>{const s=block.trim();if(!s)return"";if(s==="---")return"<hr>";if(s.startsWith("### "))return"<h3>"+inline(s.slice(4))+"</h3>";if(s.startsWith("## "))return"<h2>"+inline(s.slice(3))+"</h2>";if(s.startsWith("# "))return"<h1>"+inline(s.slice(2))+"</h1>";if(s.split("\n").every(x=>/^[-*] /.test(x)))return"<ul>"+s.split("\n").map(x=>"<li>"+inline(x.slice(2))+"</li>").join("")+"</ul>";if(s.split("\n").every(x=>/^\d+\. /.test(x)))return"<ol>"+s.split("\n").map(x=>"<li>"+inline(x.replace(/^\d+\. /,""))+"</li>").join("")+"</ol>";if(s.startsWith("&gt; "))return"<blockquote>"+inline(s.slice(5).replace(/\n/g," "))+"</blockquote>";return"<p>"+inline(s.replace(/\n/g,"<br>"))+"</p>"}).join("")}
function inline(s){return s.replace(/\*\*(.+?)\*\*/g,"<strong>$1</strong>").replace(/\*(.+?)\*/g,"<em>$1</em>").replace(/\[([^\]]+)\]\((https?:\/\/[^)]+)\)/g,'<a href="$2" target="_blank" rel="noopener noreferrer">$1</a>')}
function updatePreview(){const p=attachmentPaths();$("#preview-meta").textContent=[fields.issue_number.value&&"№ "+fields.issue_number.value,fields.date.value,fields.theme.value].filter(Boolean).join(" · ")||"Черновик";$("#preview-heading").textContent=fields.title.value||"Новый выпуск";$("#preview-summary").textContent=fields.summary.value;$("#preview-body").innerHTML=md(fields.body.value||"Здесь появится текст выпуска…")+(p.length?'<div class="preview-files"><b>Материалы: '+p.length+'</b><span>'+p.map(x=>escapeHtml(x.split("/").pop())).join(" · ")+"</span></div>":"");filenameEl.textContent=chosenFilename();const base="https://github.com/"+REPO;githubLink.href=sourceFile?base+"/edit/"+BRANCH+"/"+FOLDER+"/"+encodeURIComponent(sourceFile):base+"/new/"+BRANCH+"/"+FOLDER+"?filename="+encodeURIComponent(chosenFilename())}
function updateStats(){const text=fields.body.value.trim(),words=text?text.split(/\s+/).length:0,articles=(text.match(/^##\s+/gm)||[]).length;$("#word-count").textContent=words+" "+plural(words,"слово","слова","слов");$("#char-count").textContent=text.length+" "+plural(text.length,"знак","знака","знаков");$("#article-count").textContent=articles?"· "+articles+" "+plural(articles,"статья","статьи","статей"):""}
function plural(n,one,few,many){const x=Math.abs(n)%100,y=x%10;return x>10&&x<20?many:y>1&&y<5?few:y===1?one:many}
function fill(issue,origin=""){names.forEach(n=>fields[n].value=clean(issue[n]));sourceFile=origin;attachments=[];if(issue.file)attachments.push({id:"published-main",name:String(issue.file).split("/").pop(),type:"опубликованный файл",size:0,published:true,path:issue.file,primary:true});if(Array.isArray(issue.attachments))issue.attachments.forEach((p,i)=>attachments.push({id:"published-"+i,name:String(p).split("/").pop(),type:"опубликованный файл",size:0,published:true,path:p,primary:!issue.file&&i===0}));updatePreview();updateStats();renderFiles()}
async function loadIssues(){try{const r=await fetch("../content/issues.json",{cache:"no-store"});if(!r.ok)throw Error();issues=await r.json();issues.forEach((x,i)=>{const o=document.createElement("option");o.value=String(i);o.textContent=(x.issue_number?"№ "+x.issue_number+" · ":"")+x.title;chooser.append(o)});catalogueStatus.textContent="Опубликовано выпусков: "+issues.length+". Черновик сохраняется автоматически."}catch{catalogueStatus.textContent="Архив недоступен, но локальный редактор продолжает работать."}}
function clearArticle(){Object.values(article).forEach(x=>x.value="");article.section.value="Новости";article.title.focus()}
function addArticle(){const title=clean(article.title.value),text=clean(article.text.value),lead=clean(article.lead.value);if(!title||(!text&&!lead)){status.textContent="Для статьи нужен заголовок и текст или лид.";article.title.focus();return}const meta=[clean(article.section.value),clean(article.author.value)&&"Автор: "+clean(article.author.value)].filter(Boolean).join(" · ");let block="## "+title+"\n\n";if(meta)block+="**"+meta+"**\n\n";if(lead)block+=lead+"\n\n";if(text)block+=text+"\n";const current=fields.body.value.trim();fields.body.value=(current?current+"\n\n---\n\n":"")+block.trim()+"\n";if(!fields.summary.value.trim()&&lead)fields.summary.value=lead.slice(0,600);clearArticle();scheduleSave();status.textContent="Статья добавлена в выпуск."}
const templates={news:{section:"Новости",title:"Заголовок новости",lead:"Самое важное — одним предложением",text:"Что произошло?\n\nКто участвовал?\n\nПочему это важно?"},interview:{section:"Интервью",title:"Интервью с…",lead:"Кто герой интервью и о чём разговор",text:"— Вопрос?\n— Ответ.\n\n— Следующий вопрос?\n— Ответ."},announcement:{section:"Афиша",title:"Скоро в лицее…",lead:"Что, где и когда",text:"Дата и время:\nМесто:\nДля кого:\n\nПодробности:"},opinion:{section:"Мнение",title:"Заголовок колонки",lead:"Главная мысль автора",text:"Тезис.\n\nАргументы и примеры.\n\nВывод."},blank:{section:"",title:"",lead:"",text:""}};
document.querySelectorAll("[data-template]").forEach(b=>b.onclick=()=>{const t=templates[b.dataset.template];article.section.value=t.section;article.title.value="";article.lead.value="";article.text.value="";article.title.placeholder=t.title||"Заголовок статьи";article.lead.placeholder=t.lead||"Короткий лид";article.text.placeholder=t.text||"Текст статьи";article.title.focus();scheduleSave()});
chooser.onchange=()=>{if(chooser.value===""){restoreDraft();renderFiles();updatePreview();updateStats();return}const x=issues[Number(chooser.value)];if(x)fill(x,x.source_file||"")};
fileInput.onchange=async()=>{await addFiles([...fileInput.files]);fileInput.value=""};photoInput.onchange=async()=>{await addFiles([...photoInput.files]);photoInput.value=""};cameraInput.onchange=async()=>{await addFiles([...cameraInput.files]);cameraInput.value=""};
$("#pick-files").onclick=()=>fileInput.click();$("#pick-photos").onclick=()=>photoInput.click();$("#take-photo").onclick=()=>cameraInput.click();
["dragenter","dragover"].forEach(ev=>dropZone.addEventListener(ev,e=>{e.preventDefault();dropZone.classList.add("dragging")}));["dragleave","drop"].forEach(ev=>dropZone.addEventListener(ev,e=>{e.preventDefault();dropZone.classList.remove("dragging")}));dropZone.addEventListener("drop",e=>addFiles([...e.dataTransfer.files]));
document.addEventListener("paste",e=>{const files=[...e.clipboardData.files].filter(f=>f.type.startsWith("image/"));if(files.length){addFiles(files);status.textContent="Изображение из буфера добавлено к выпуску."}});
form.addEventListener("input",scheduleSave);Object.values(article).forEach(x=>x.addEventListener("input",scheduleSave));
$("#save-local").onclick=()=>saveDraft(true);$("#add-article").onclick=addArticle;$("#clear-article").onclick=clearArticle;
$("#new").onclick=()=>{names.forEach(n=>fields[n].value="");fields.date.value=today();attachments=[];sourceFile="";chooser.value="";clearArticle();saveDraft(false);renderFiles();updatePreview();updateStats();status.textContent="Создан новый локальный выпуск."};
$("#clear-local").onclick=()=>{localStorage.removeItem(DRAFT_KEY);status.textContent="Локальный черновик очищен."};
document.querySelectorAll(".toolbar button").forEach(b=>b.onclick=()=>{const t=fields.body,action=b.dataset.action;if(action==="undo"||action==="redo"){t.focus();document.execCommand(action);scheduleSave();return}const start=t.selectionStart,end=t.selectionEnd,sel=t.value.slice(start,end);if(b.dataset.wrap){const [a,z]=b.dataset.wrap.split("|");t.setRangeText(a+sel+z,start,end,"select")}else if(b.dataset.prefix){const line=t.value.lastIndexOf("\n",start-1)+1;t.setRangeText(b.dataset.prefix,line,line,"end")}else if(action==="link"){const url=prompt("Ссылка","https://");if(url)t.setRangeText("["+(sel||"ссылка")+"]("+url+")",start,end,"end")}else if(action==="rule"){t.setRangeText("\n\n---\n\n",start,end,"end")}t.focus();scheduleSave()});
document.addEventListener("keydown",e=>{const mod=e.ctrlKey||e.metaKey;if(mod&&e.key.toLowerCase()==="s"){e.preventDefault();saveDraft(true)}if(mod&&e.key==="Enter"&&(document.activeElement===article.text||document.activeElement===article.title||document.activeElement===article.lead)){e.preventDefault();addArticle()}if(mod&&(e.key.toLowerCase()==="b"||e.key.toLowerCase()==="i")&&document.activeElement===fields.body){e.preventDefault();const mark=e.key.toLowerCase()==="b"?"**":"*",t=fields.body,s=t.selectionStart,en=t.selectionEnd;t.setRangeText(mark+t.value.slice(s,en)+mark,s,en,"select");scheduleSave()}});
$("#download").onclick=()=>{const blob=new Blob([makeMarkdown()],{type:"text/markdown;charset=utf-8"}),a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=chosenFilename();a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);status.textContent="Markdown выпуска сохранён на устройство."};$("#copy").onclick=async()=>{try{await navigator.clipboard.writeText(makeMarkdown());status.textContent="Markdown скопирован."}catch{status.textContent="Браузер запретил копирование — используй «Экспорт .md»."}};
if(!restoreDraft()){fields.date.value=today();article.section.value="Новости"}renderFiles();updatePreview();updateStats();loadIssues();
