"use strict";
const REPO="Azotishka/Neuro-assistent",FOLDER="content/issues",BRANCH="gh-pages",DRAFT_KEY="luch:draft:v3",DB_NAME="luch-editor-v1",STORE="files";
const names=["title","issue_number","date","theme","summary","body"],form=document.querySelector("#issue-form"),chooser=document.querySelector("#existing"),status=document.querySelector("#publish-status"),catalogueStatus=document.querySelector("#catalogue-status"),fileInput=document.querySelector("#attachment"),fileList=document.querySelector("#file-list"),fileCount=document.querySelector("#file-count"),filePreview=document.querySelector("#attachment-preview"),githubLink=document.querySelector("#github-link"),filenameEl=document.querySelector("#filename");
const fields=Object.fromEntries(names.map(n=>[n,document.getElementById(n)]));let issues=[],sourceFile="",attachments=[],saveTimer=0,previewUrl="";
const today=()=>{const d=new Date(Date.now()-new Date().getTimezoneOffset()*60000);return d.toISOString().slice(0,10)},clean=v=>String(v??"").trim();
function slug(v){return clean(v).toLowerCase().normalize("NFKD").replace(/[\u0300-\u036f]/g,"").replace(/[^a-z0-9а-яё]+/g,"-").replace(/^-+|-+$/g,"").slice(0,48)}
function chosenFilename(){if(sourceFile)return sourceFile;return (/^\d{4}-\d{2}-\d{2}$/.test(fields.date.value)?fields.date.value:today())+"-issue-"+(slug(fields.issue_number.value).replace(/[^a-z0-9-]/g,"")||"new")+"-"+(slug(fields.title.value).replace(/[^a-z0-9-]/g,"")||"news")+".md"}
function paths(){return attachments.filter(x=>!x.published).map(x=>"content/files/"+x.name)}
function makeMarkdown(){const meta={title:clean(fields.title.value),issue_number:clean(fields.issue_number.value),date:clean(fields.date.value),theme:clean(fields.theme.value),summary:clean(fields.summary.value),file:paths()[0]||"",attachments:JSON.stringify(paths().slice(1))};return "---\n"+Object.entries(meta).map(([k,v])=>k+": "+JSON.stringify(v)).join("\n")+"\n---\n\n"+fields.body.value.trim()+"\n"}
function draft(){return {fields:Object.fromEntries(names.map(n=>[n,fields[n].value])),attachments:attachments.filter(x=>!x.published),sourceFile,updatedAt:new Date().toISOString()}}
function saveDraft(message=true){localStorage.setItem(DRAFT_KEY,JSON.stringify(draft()));if(message)status.textContent="Черновик сохранён на этом устройстве."}
function scheduleSave(){clearTimeout(saveTimer);saveTimer=setTimeout(()=>saveDraft(false),350);updatePreview()}
function restoreDraft(){try{const d=JSON.parse(localStorage.getItem(DRAFT_KEY)||"null");if(!d)return false;names.forEach(n=>fields[n].value=d.fields?.[n]||"");attachments=Array.isArray(d.attachments)?d.attachments:[];sourceFile=d.sourceFile||"";return true}catch{return false}}
function db(){return new Promise((ok,no)=>{const r=indexedDB.open(DB_NAME,1);r.onupgradeneeded=()=>r.result.createObjectStore(STORE,{keyPath:"id"});r.onsuccess=()=>ok(r.result);r.onerror=()=>no(r.error)})}
async function putFile(file,id){const d=await db();return new Promise((ok,no)=>{const r=d.transaction(STORE,"readwrite").objectStore(STORE).put({id,name:file.name,type:file.type,size:file.size,blob:file});r.onsuccess=()=>ok();r.onerror=()=>no(r.error)})}
async function getFile(id){const d=await db();return new Promise((ok,no)=>{const r=d.transaction(STORE).objectStore(STORE).get(id);r.onsuccess=()=>ok(r.result);r.onerror=()=>no(r.error)})}
async function delFile(id){const d=await db();return new Promise((ok,no)=>{const r=d.transaction(STORE,"readwrite").objectStore(STORE).delete(id);r.onsuccess=()=>ok();r.onerror=()=>no(r.error)})}
function human(n){if(!n)return "опубликован";if(n<1024)return n+" Б";if(n<1048576)return (n/1024).toFixed(1)+" КБ";return (n/1048576).toFixed(1)+" МБ"}
async function addFiles(files){for(const f of files){const ext=(f.name.split(".").pop()||"").toLowerCase();if(!/^(pdf|doc|docx|odt|rtf|txt|md|ppt|pptx|xls|xlsx|csv|jpg|jpeg|png|webp|zip)$/.test(ext)||f.size>25*1024*1024){status.textContent="Пропущен файл "+f.name+": неподдерживаемый формат или больше 25 МБ.";continue}const id=crypto.randomUUID();await putFile(f,id);attachments.push({id,name:f.name,type:f.type||"application/octet-stream",size:f.size});if(/^(txt|md|csv)$/.test(ext)){const t=await f.text();if(!fields.body.value.trim())fields.body.value=t.slice(0,120000)}}saveDraft(false);renderFiles();updatePreview()}
async function renderFiles(){fileList.replaceChildren();fileCount.textContent=attachments.length+" файл"+(attachments.length===1?"":attachments.length<5?"а":"ов");for(const a of attachments){const row=document.createElement("div");row.className="file-row";row.innerHTML='<div><strong>'+escapeHtml(a.name)+'</strong><small>'+escapeHtml(a.type||"файл")+' · '+human(a.size)+'</small></div><div class="file-actions"><button type="button" data-open>Открыть</button><button type="button" data-remove>×</button></div>';const open=row.querySelector("[data-open]"),remove=row.querySelector("[data-remove]");if(a.published){open.onclick=()=>window.open("../"+a.path,"_blank","noopener");remove.disabled=true}else{open.onclick=()=>previewAttachment(a.id);remove.onclick=async()=>{await delFile(a.id);attachments=attachments.filter(x=>x.id!==a.id);saveDraft(false);renderFiles();updatePreview()}}fileList.append(row)}}
async function previewAttachment(id){const rec=await getFile(id);if(!rec)return;if(previewUrl)URL.revokeObjectURL(previewUrl);previewUrl=URL.createObjectURL(rec.blob);filePreview.replaceChildren();const ext=rec.name.split(".").pop().toLowerCase();if(ext==="pdf"){const f=document.createElement("iframe");f.src=previewUrl;f.title=rec.name;filePreview.append(f)}else if(/^(jpg|jpeg|png|webp)$/.test(ext)){const img=document.createElement("img");img.src=previewUrl;img.alt=rec.name;filePreview.append(img)}else{const box=document.createElement("div");box.className="file-open";box.innerHTML="<b>"+escapeHtml(rec.name)+"</b><p>Формат сохранён целиком вместе со встроенным текстом, изображениями и оформлением.</p>";const a=document.createElement("a");a.href=previewUrl;a.download=rec.name;a.textContent="Открыть / скачать файл";box.append(a);filePreview.append(box)}}
function escapeHtml(v){return String(v??"").replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;").replace(/'/g,"&#39;")}
function md(src){const safe=escapeHtml(src);return safe.split(/\n{2,}/).map(block=>{const s=block.trim();if(!s)return"";if(s.startsWith("### "))return"<h3>"+inline(s.slice(4))+"</h3>";if(s.startsWith("## "))return"<h2>"+inline(s.slice(3))+"</h2>";if(s.startsWith("# "))return"<h1>"+inline(s.slice(2))+"</h1>";if(s.split("\n").every(x=>x.startsWith("- ")))return"<ul>"+s.split("\n").map(x=>"<li>"+inline(x.slice(2))+"</li>").join("")+"</ul>";if(s.startsWith("&gt; "))return"<blockquote>"+inline(s.slice(5).replace(/\n/g," "))+"</blockquote>";return"<p>"+inline(s.replace(/\n/g,"<br>"))+"</p>"}).join("")}
function inline(s){return s.replace(/\*\*(.+?)\*\*/g,"<strong>$1</strong>").replace(/\*(.+?)\*/g,"<em>$1</em>")}
function updatePreview(){document.querySelector("#preview-meta").textContent=[fields.issue_number.value&&"№ "+fields.issue_number.value,fields.date.value,fields.theme.value].filter(Boolean).join(" · ")||"Черновик";document.querySelector("#preview-heading").textContent=fields.title.value||"Новый выпуск";document.querySelector("#preview-summary").textContent=fields.summary.value;document.querySelector("#preview-body").innerHTML=md(fields.body.value||"Здесь появится текст выпуска…");filenameEl.textContent=chosenFilename();const base="https://github.com/"+REPO;githubLink.href=sourceFile?base+"/edit/"+BRANCH+"/"+FOLDER+"/"+encodeURIComponent(sourceFile):base+"/new/"+BRANCH+"/"+FOLDER+"?filename="+encodeURIComponent(chosenFilename())}
function fill(issue,origin=""){names.forEach(n=>fields[n].value=clean(issue[n]));sourceFile=origin;attachments=[];if(issue.file){attachments.push({id:"published-main",name:String(issue.file).split("/").pop(),type:"опубликованный файл",size:0,published:true,path:issue.file})}if(Array.isArray(issue.attachments))issue.attachments.forEach((p,i)=>attachments.push({id:"published-"+i,name:String(p).split("/").pop(),type:"опубликованный файл",size:0,published:true,path:p}));updatePreview();renderFiles()}
async function loadIssues(){try{const r=await fetch("../content/issues.json",{cache:"no-store"});if(!r.ok)throw Error();issues=await r.json();issues.forEach((x,i)=>{const o=document.createElement("option");o.value=String(i);o.textContent=(x.issue_number?"№ "+x.issue_number+" · ":"")+x.title;chooser.append(o)});catalogueStatus.textContent="Опубликовано выпусков: "+issues.length+". Черновик хранится отдельно на этом устройстве."}catch{catalogueStatus.textContent="Архив недоступен, но локальный редактор продолжает работать."}}
chooser.onchange=()=>{if(chooser.value===""){restoreDraft();renderFiles();updatePreview();return}const x=issues[Number(chooser.value)];if(x)fill(x,x.source_file||"")};
fileInput.onchange=async()=>{await addFiles([...fileInput.files]);fileInput.value=""};form.addEventListener("input",scheduleSave);document.querySelector("#save-local").onclick=()=>saveDraft(true);document.querySelector("#new").onclick=()=>{names.forEach(n=>fields[n].value="");fields.date.value=today();attachments=[];sourceFile="";chooser.value="";saveDraft(false);renderFiles();updatePreview();status.textContent="Создан новый локальный черновик."};document.querySelector("#clear-local").onclick=()=>{localStorage.removeItem(DRAFT_KEY);status.textContent="Локальный черновик очищен."};
document.querySelectorAll(".toolbar button").forEach(b=>b.onclick=()=>{const t=fields.body,start=t.selectionStart,end=t.selectionEnd,sel=t.value.slice(start,end);if(b.dataset.wrap){const [a,z]=b.dataset.wrap.split("|");t.setRangeText(a+sel+z,start,end,"select")}else{const line=t.value.lastIndexOf("\n",start-1)+1;t.setRangeText(b.dataset.prefix||"",line,line,"end")}t.focus();scheduleSave()});
document.querySelector("#download").onclick=()=>{const blob=new Blob([makeMarkdown()],{type:"text/markdown;charset=utf-8"}),a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=chosenFilename();a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);status.textContent="Markdown выпуска сохранён на устройство."};document.querySelector("#copy").onclick=async()=>{try{await navigator.clipboard.writeText(makeMarkdown());status.textContent="Markdown скопирован."}catch{status.textContent="Браузер запретил копирование — используй «Экспорт .md»."}};
if(!restoreDraft()){fields.date.value=today();fields.title.value="ЛУЧ — Лучшее утро четверга"}renderFiles();updatePreview();loadIssues();
